### ISSUE TITLE
Typography fixes

### ISSUE THREAD

**Issue by oveddan** [itpresidents/thesis-archive-2020#50]
per @ilanabonder  via slack:
* the Thesis Projects Titles in the homepage are Dark Gray and they should be black. Maybe this happened once you changed the mobile text styling (just be mindful to check there if anything changes once you set that back to black).

```css
@media (min-width: 768px)
typography.scss:39
#details figure figcaption, .description{
 margin-top: 10px;
 font-style: italic;
 font-size: 0.9rem;
 line-height: 1.2rem;
}
```
